# export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
# export PATH=$JAVA_HOME/bin:$PATH

language: java
jdk: oraclejdk8
install: true
script: ./mvn clean install
cache:
  directories:
  - $HOME/.m2
